# Dockerfile
FROM node:18.19.1-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install --force

COPY . .
RUN npm run build

FROM node:18.19.1-alpine

WORKDIR /app

COPY --from=build /app .

EXPOSE 3000

CMD ["node", "build"]
